"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true 

format = """[](fg:#c9c9c9)[ $directory](bg:#c9c9c9 fg:#0f080e)[](fg:#c9c9c9) 
> """

right_format = "[](fg:#c9c9c9)[$git_branch /$git_metrics ](bg:#c9c9c9 fg:#0f080e)[](fg:#c9c9c9) [](fg:#c9c9c9)[ $status](bg:#c9c9c9 fg:#0f080e)[](fg:#c9c9c9)"

[status]
symbol = " "
success_symbol = " "
disabled = false
format = '$symbol'

[directory]
disabled = false
format = "[$path](bg:#c9c9c9 fg:#0f080e) "

[git_branch]
symbol = ' '
format = '[$symbol$branch](bg:#c9c9c9 fg:#0f080e)'

[git_metrics]
disabled = false
only_nonzero_diffs = false
format = '[  $added  $deleted](bg:#c9c9c9 fg:#0f080e)'

